MD013: false     # Line length
MD024: false     # Multiple headers with the same content
MD033: false     # Inline HTML [Element: details] [Element: summary]
MD036: false     # Emphasis used instead of a heading
